### ISSUE TITLE
스토리지센터 가상머신 배포 상태 조회

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#10]
## 개발 개요
스토리지센터 가상머신 배포 상태 조회
## 개발 기능
- virsh 명령어를 이용하여 스토리지 센터 VM 배포 상태 확인
- 스토리지 가상머신의 호스트명은 **SCVM** 으로 픽스

**Comment by jschoiRR** [comment]
제가하겠습니다.

**Comment by jschoiRR** [comment]
#8 해당 이슈와 링크되어 이슈 해결 됨
