### ISSUE TITLE
스토리지센터 VM 배포 마법사 UI

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-cockpit-plugin#12]
## 개발 개요
스토리지센터 VM 배포를 위한 마법사 UI 개발
## 개발 기능
- Compute 정보 설정 UI
- Network 정보 설정 UI
- Disk 정보 설정 UI
- hosts 파일 업로드 UI
- ssh key 파일 업로드 UI
- 가상머신 리뷰 및 배포 시작 UI
- 진행상태 조회 UI

**Comment by jschoiRR** [comment]
제가하겠습니다.

**Comment by qoxown12** [comment]
제가 하겠습니다.
