### ISSUE TITLE
클러스터 구성 준비 관련 기능 개선

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#125]
## 개발 개요
클러스터 구성 준비 진행이 완료된 경우 ablestack 페이지 새로고침하도록 기능 개선
ssh-key 600 권한 지정 필요
 
## 개발 기능
기능에 대한 설명 및 주요 개발 내역

**Comment by stardom3645** [comment]
제가 하겠습니다.

**Comment by SeockMin** [comment]
+ ssh-key 권한 변경 필요(600)

**Comment by stardom3645** [comment]
연관 pull request
-클러스터 준비 마법사 SSH Key, hosts파일 기능 개선 및 UI 버그 수정 #123
