### ISSUE TITLE
스토리지 가상머신 배포시 오류

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#126]
**Bug 개요**
스토리지 가상머신 배포 마법사에서 배포 버튼을 누르고 진행중인 단계에서 에러 alert 출력되지만, 실제 VM은 실행중인 상태

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by qoxown12** [comment]
이미 처리 되어있습니다.
