### ISSUE TITLE
호스트 추가 후 다른 호스트의 페이지에 접근한 경우 상태조회 오류

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#127]
**Bug 개요**
호스트 추가 후 다른 호스트의 페이지에 접근한 경우 상태조회 오류로 spawn 명령어 실행 시 localhost 를 바라보지않도록 변경필요

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. 왼쪽 상단 호스트 추가
2. 현재 호스트 cockpit에서 다른 호스트 cockpit으로 접속하여 ablestack 메뉴 클릭

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by Dajeong-Park** [comment]
@박다정 주임
