### ISSUE TITLE
scvm root 계정으로 로그인 안되는 오류

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#128]
**Bug 개요**
scvm root 계정으로 로그인 안되는 오류

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. scvm cockpit root 로그인

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by ycyun** [comment]
#134 와 같이 root 계정 로그인을 금지하는것으로 하겠습니다.
