### ISSUE TITLE
scvm 상태조회시 ROOT Disk 크기 조회오류

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#129]
**Bug 개요**
호스트에 virsh pool-list 명령어로 결과값이 없는 경우 상태에서 ROOT Disk 크기를 조회할 수 없는 부분처리 필요

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. 하나의 호스트에만 default pool 생성된 경우에 발생

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by jschoiRR** [comment]
@jschoiRR 최진성책임

**Comment by jschoiRR** [comment]
virsh vol-info ~
=> virsh domblkinfo --domain scvm --human --all | grep vda 변경하여 조회되도록 변경
