### ISSUE TITLE
scvm 삭제 모달 개선

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#130]
## 개발 개요
scvm 삭제 시 모달 버튼을 변경->삭제 로 개선
 
## 개발 기능
scvm 삭제 버튼 선택한 경우 모달에 변경버튼을 삭제버튼으로 변경하도록 개선

**Comment by jschoiRR** [comment]
@jschoiRR 최진성책임
