### ISSUE TITLE
scvm 관련 액션 버튼 활성화/비활성화 

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#132]
**Bug 개요**
scvm running중인 상태에서 scvm 정지 버튼이 활성화되지않는 오류

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. scvm running중인 상태에서 scvm 정지버튼이 활성화되지않음

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by jschoiRR** [comment]
@jschoiRR 최진성책임
