### ISSUE TITLE
스토리지센터 연결 오류

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#133]
**Bug 개요**
스토리지센터 연결 오류 

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. 스토리지센터 연결 버튼 클릭시 오류 (로직변경 필요)
2. 초기상태에서 scvm1에 mgr 설정 시 scvm1에서만 ceph 명령어가 가능하기 때문에 초기상태에 대한 고려가 필요함

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by Dajeong-Park** [comment]
@박다정 주임
