### ISSUE TITLE
scvm shell 파일 작성

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#135]
## 개발 개요
scvm 배포 후 수동작업을 자동화하도록 shell 파일 작성 필요 

## 개발 기능
scvm 배포 후 수동작업을 자동화하도록 shell 파일 작성 필요

**Comment by ycyun** [comment]
제가 하겠습니다

**Comment by ycyun** [comment]
- [ ] bootstrap 작업
- [ ] ceph.conf, ceph.client.admin.keyring 배포작업
- [ ] 초기 설정 작업

**Comment by ycyun** [comment]
bootstrap 작업내용
image=$(/bin/podman inspect --format {{.ID}},{{.RepoDigests}} docker-archive:/usr/share/ablestack/ablestack.tar:localhost/ceph/daemon:ablestack | cut -d "," -f 2 | sed 's/\[//' | sed 's/]//' )  #이미지파일의 해시 분석
cephadm --image $image bootstrap \
	--initial-dashboard-user ablestack \
	--initial-dashboard-password Ablecloud1! \
	--ssh-private-key /root/.ssh/id_rsa \
	--ssh-public-key /root/.ssh/id_rsa.pub \
	--no-minimize-config \
	--skip-pull \
	--allow-overwrite \
	--mon-ip 100.100.1.11 \
	--cluster-network 100.200.1.0/24 \
	--with-exporter #for simple api https://docs.ceph.com/en/latest/dev/cephadm/cephadm-exporter/

#컨테이너 이미지 지정
ceph config set global container_image $image
ceph config set global mgr/cephadm/container_image_base $image

#ceph환경설정
ceph config set client rbd_cache_policy writeback
ceph config set client rbd_cache_size 1073741824
ceph config set client rbd_cache_max_dirty 805306368
ceph config set client rbd_cache_target_dirty 536870912
ceph config set client rbd_cache_max_dirty_age 5.0

#ceph host정보 설정
hosts=$(cat /etc/hosts|grep scvm | grep -v mngt | cut -d " " -f 1)
echo "[global]" > $conffile
echo -n -e "\tmon_host = " >> $conffile
for host in $hosts
do 
	echo -n "[v2:$host:3300/0,v1:$host:6789/0], " >> $conffile
done

#ceph 설정정보 배포
for host in $hosts
do
	scp /etc/ceph/* $host:/etc/ceph
done

**Comment by ycyun** [comment]
cloudinit iso 생성시 leader와 나머지를 구분하는 파라미터도 추가가 필요합니다.
