### ISSUE TITLE
kickstart pcs 방화벽 추가 

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#137]
**Bug 개요**
pcs cluster 구성 오류로 kickstart에 pcs 서비스 방화벽 추가 필요

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. 클라우드센터 가상머신 배포시 클러스터 구성 진행중 오류

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by kt-cheon** [comment]
해당 이슈는 ablestack-kickstart 레파지토리에서 이슈를 생성하고 처리하였습니다.

**Comment by leca777** [comment]
[kickstart 방화벽 추가](https://github.com/ablecloud-team/ablestack-kickstart/issues/4) 로 처리
