### ISSUE TITLE
스토리지센터 가상머신 삭제

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#15]
## 개발 개요
스토리지센터 가상머신을 삭제하는 기능
## 개발 기능
스토리지센터 클러스터 구성 전단계에서 잘못 설정된 가상머신을 삭제하기 위한 기능

**Comment by jschoiRR** [comment]
제가하겠습니다.

**Comment by jschoiRR** [comment]
![image](https://user-images.githubusercontent.com/77760789/111281223-0dc6cb80-8680-11eb-940b-dcf8cb80288a.png)
