### ISSUE TITLE
방화벽 VNC port 변경

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#169]
## 개발 개요
방화벽 VNC port 변경 (5000 ~ 6000)
## 개발 기능
기능에 대한 설명 및 주요 개발 내역

**Comment by kt-cheon** [comment]
@kt-cheon

**Comment by kt-cheon** [comment]
해당 이슈는 ablestack-kickstart repository에서 해결하였습니다.
