### ISSUE TITLE
ceph exporter 제거

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#196]
**Bug 개요**
ceph exporter 제거

**Bug 발생 경위**

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by ycyun** [comment]
제가 하겠습니다.
