### ISSUE TITLE
스토리지 가상머신 상태 UI

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#20]
## 개발 개요
스토리지 가상머신 상태 UI
## 개발 기능
스토리지 가상머신 동작상태
스토리지 가상머신 CPU, Memony등의 표시
스토리지 가상머신 시작, 정지 관리
스토리지 가상머신 삭제
## 기타

**Comment by jschoiRR** [comment]
제가하겠습니다.

**Comment by jschoiRR** [comment]
![image](https://user-images.githubusercontent.com/77760789/111281170-fdaeec00-867f-11eb-864f-55ca11d75883.png)
