### ISSUE TITLE
스토리지 가상머신 삭제시 /etc/ceph 하위경로 삭제하도록 추가

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cockpit-plugin#202]
**Bug 개요**
스토리지 가상머신 삭제시 /etc/ceph 하위경로 삭제하도록 추가 

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. 스토리지 가상머신 삭제 완료 후 상태조회

**예측 결과**
예측되는 결과

**실제 결과**
실제 발생한 결과

**화면캡쳐**
필요시 Bug를 설명하는데 도움이 되는 스크린 샷등을 추가

**실행환경**
Bug 발생시 실행 환경

**추가사항**
기타사항

**Comment by jschoiRR** [comment]
@jschoiRR 최진성책임
