### ISSUE TITLE
스토리지센터 가상머신 배포 오류 (qcow2파일)

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cockpit-plugin#225]
**Bug 개요**
ablestack-template-copy.qcow2 -> ablestack-template-back.qcow2 파일로 변경해야함

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. 스토리지센터 가상머신 배포 진행 중 오류

**Comment by kt-cheon** [comment]
해당 이슈는 재구성 할 당시 copy.qcow2 파일로 잘못 복사하여 생긴 이슈입니다.
최초 파일은 ablestack-template.qcow2 파일과 ablestack-template-back.qcow2(backing file)로 되어 있습니다.
이슈를 close 하셔도 됩니다.
