### ISSUE TITLE
scvm 시간서버 설정 확인 시 호스트를 보지않는 오류

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cockpit-plugin#229]
**Bug 개요**
시간 서버(로컬) 설정 시 scvm은 호스트를 보지않는 오류

**Bug 발생 경위**
Bug가 발생하게된 경위(재현하기 위한 절차):
1. scvm 시간서버 설정 확인

**Comment by kt-cheon** [comment]
scvm의 chrony.conf 파일에
server ablecube iburst 라인을 추가하여 자신의 host를 시간서버 마스터로 동기화 할 수 있도록 변경하였습니다.
해당 이슈는 qcow2 template에서 작업하여 별도의 pr이 없습니다.
