### ISSUE TITLE
스토리지 및 클라우드센터 가상머신 상태 관리 NIC 넷마스크 추가

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cockpit-plugin#231]
## 개발 개요
스토리지 및 클라우드센터 가상머신 상태 관리 NIC 항목에 넷마스크 추가

## 개발 기능
스토리지 및 클라우드센터 가상머신 상태 관리 NIC 항목에 넷마스크 추가

**Comment by jschoiRR** [comment]
@jschoiRR 최진성책임
