### ISSUE TITLE
ABLESTACK 스토리지 클러스터 상태 항목 변경

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/ablestack-cockpit-plugin#247]
ABLESTACK 스토리지 클러스터 상태 박스의 게이트웨이 항목의 내용에 대한 수정이 필요

현재는 RBD GW 3개 제공중(quorum : scvm-f1,scvm-f3) 와 같이 제공 중인 내용만 표기가 되지만 호스트 장애등으로 인하여 2개만 실행 중일 경우에 대한 식별하기가 어려움

따라서 실행중/제공중 과 같은 형태로 변경이 필요

**Comment by jschoiRR** [comment]
@jschoiRR
