### ISSUE TITLE
클라우드 센터의 클라우드 상태가 클러스터 노드가 하나 죽어도 정상 상태로 표기

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/ablestack-cockpit-plugin#248]
클라우드 센터의 클라우드 상태가 클러스터 노드가 하나 죽어도 정상 상태로 표기

**Comment by kt-cheon** [comment]
@kt-cheon

**Comment by kt-cheon** [comment]
python PCS 조회 부분(backend)은 호스트의 online/offline을 조회할 수 있도록 하여 pr 완료 했습니다.
cube(cockpit) 화면에서의 조회 부분은 추가 개발이 필요합니다.
@SeockMin
