### ISSUE TITLE
클라우드센터 가상머신 상세조회

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#25]
## 개발 개요
클라우드센터 가상머신 상세조회
## 개발 기능
클라우드센터 가상머신의 동작상태
클라우드센터 가상머신의 CPU, Memory등의 사용량

**Comment by jschoiRR** [comment]
제가하겠습니다

**Comment by jschoiRR** [comment]
@ycyun 에게 이슈 전달합니다.

**Comment by jschoiRR** [comment]
참고하세요
![Uploading image.png…]()

**Comment by ycyun** [comment]
#35 와 연계됨
- [ ] 클라우드센터 가상머신의 동작상태
- [ ] 클라우드센터 가상머신의 CPU, Memory등의 사용량

**Comment by ycyun** [comment]
merge 되었으니 close 하겠습니다
