### ISSUE TITLE
스토리지센터 클러스터상태 UI

### ISSUE THREAD

**Issue by SeockMin** [ablecloud-team/ablestack-cockpit-plugin#26]
## 개발 개요
스토리지센터 클러스터상태 UI
## 개발 기능
스토리지센터 클러스터상태 UI 개발

**Comment by jschoiRR** [comment]
가져갑니다

**Comment by jschoiRR** [comment]
![image](https://user-images.githubusercontent.com/77760789/111281009-d1936b00-867f-11eb-9ecb-7f322b90d615.png)
