### ISSUE TITLE
2021.05.04 회의내용 정리

### ISSUE THREAD

**Issue by gigs4014** [ablecloud-team/ablestack-cockpit-plugin#263]
### Mold
- 메인 가이드 경로 및 각 메뉴별 가이드 ablecloud.io 로 적용
- 호스트 추가시 SSH 포트 변경 하는 방법(글로벌 설정에 추가하여 포트를 변경할 수 있도록 개선)

### Wall
- 모니터링 데이터 수집 방안 연구 : node-expoter, windows-exporter, libvirt-exporter
- 리얼 데이터 수집 방법 연구
- 토폴로지 연구
- 모니터링 조회 사용자 관리 : 계정별 자원 모니터링
- Aler, CMD 기능 추가

### Cube
- 스토리지센터 클러스터 상태 : 모니터가 죽었을 경우 모니터 재시작, mgr 재시작 등 여러 상황에 조작할 수 있는  action 필요
- 클라우드센터 클러스터 상태 : pcs 클러스터의 1개 node 가 죽었을 경우 경고로 표시되도록 개선 필요
- 메인화면상태 : 각 카드화면에서 상태 조회시 테스트는 고정하고 별도로 표시할수 있도록 재선
- 로그인 연동 : grafana, cloudstack, ceph 등 로그인 연동
- host, scvm, ccvm 등 주요 호스트 진단 보고서 내려받는 기능 추가

### Desktop as a service
- 원격접속시 SSL 관련 경고창 제거하는 방법
- password 를 입력하지 않고 로그인 가능한 방법
- samba 를 이용한 AD 구성 및 윈도우 10 도메인 가입 방법
- .rdp 파일 관련 연구
- proxy server 구성 연구
- Group Policy 연구

**Comment by leca777** [comment]
Cube의 클라우드 클러스터 상태에서 정상 일 경우는 pcs 클러스터 노드 3개가 전부 On 상태이고 클라우드 센터 VM의 상태가 정상인 경우(접속이 가능한 경우)이며 그 외의 상태는 모두 비정상으로 표기되어야 합니다

**Comment by leca777** [comment]
PCS 마이그레이션을 할 경우 이전되는 호스트가 pcs infinity 설정이 되어 나중에 장애 혹은 재부팅등으로 인하여 다른 호스트로 PCS resource가 이관된 후 infinity가 설정된 호스트로 다시 rollback이 되는 현상이 발생 하여 해당 호스트가 정상 복구가 되지 않은 상태(스토리지등)일 경우에는 PCS 실행 시도 후 실패가 되는 과정이 반복되는 현상이 발생함
이 현상에 대한 연구가 필요함

**Comment by kt-cheon** [comment]
### Cube의 클라우드 클러스터 상태에서 정상 일 경우는 pcs 클러스터 노드 3개가 전부 On 상태이고 클라우드 센터 VM의 상태가 정상인 경우(접속이 가능한 경우)이며 그 외의 상태는 모두 비정상으로 표기되어야 합니다.


pcs 클러스터 및 리소스 상태를 조회하는 python 함수에서 (python3 pcs/main.py status --resource cloudcenter_res 로 호출)
```
{
    "code": 200,
    "val": {
        "clustered_host": [
            "ablecube1",
            "ablecube2",
            "ablecube3"
        ],
        "nodes": [
            {
                "host": "ablecube1",
                "online": "true",
                "resources_running": "1",
                "standby": "false",
                "standby_onfail": "false",
                "maintenance": "false",
                "pending": "false",
                "unclean": "false",
                "shutdown": "false",
                "expected_up": "true",
                "is_dc": "true",
                "type": "member"
            },
            {
                "host": "ablecube2",
                "online": "true",
                "resources_running": "0",
                "standby": "false",
                "standby_onfail": "false",
                "maintenance": "false",
                "pending": "false",
                "unclean": "false",
                "shutdown": "false",
                "expected_up": "true",
                "is_dc": "false",
                "type": "member"
            },
            {
                "host": "ablecube3",
                "online": "true",
                "resources_running": "0",
                "standby": "false",
                "standby_onfail": "false",
                "maintenance": "false",
                "pending": "false",
                "unclean": "false",
                "shutdown": "false",
                "expected_up": "true",
                "is_dc": "false",
                "type": "member"
            }
        ],
        "started": "ablecube1",
        "role": "Started",
        "active": "true",
        "blocked": "false",
        "failed": "false"
    },
    "name": "statusResource",
    "type": "dict"
}
```
클러스터를 구성하는 모든 노드의 online 상태를 확인할 수 있게 수정하였습니다. (offline 일 경우 false,  pr 완료)
supermicro(10.10.1.1, 10.10.1.2, 10.10.1.3)에 적용했습니다. cube ui 적용이 필요합니다.
