### ISSUE TITLE
Cube 초기 접속 시 패스워드를 변경하도록 기능 개선 필요

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/ablestack-cockpit-plugin#266]
#### 이슈 타입

  * 기능 개선 요청
#### 컴포넌트 이름

~~~
UI
~~~

#### ABLESTACK 버전
 
~~~
ALLO
~~~

#### 구성

~~~
Login
~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

설치 후 최초 Cube UI에 로긴을 할 경우 패스워드를 변경하도록 수정이 필요

- root 계정에 대하여 패스워드를 임의로 만료 시켜 다음 로그인 시 패스워드를 변경하게끔 구성
```
passwd -e root
```
- 최초 패스워드는 password로 지정하여 사용자가 변경하도록 수정

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by kt-cheon** [comment]
ablestack-kickstart repository에 PR 완료 했습니다.

PR 내용 : kickstart 설치가 진행된 후 마지막에 root password를 만료 시키는 스크립트를 추가했습니다.

**Comment by leca777** [comment]
@kt-cheon 해당 이슈는 ablestack-kickstart repository에 PR 근거로 close 함
