### ISSUE TITLE
클라우드센터 가상머신 상태 UI

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#35]
## 개발 개요
클라우드센터 가상머신 상태 UI
## 개발 기능
클라우드센터 가상머신 동작상태
클라우드센터 가상머신 CPU, Memony등의 표시
클라우드센터 가상머신 시작, 정지 관리
클라우드센터 가상머신 삭제

**Comment by jschoiRR** [comment]
제가할게요

**Comment by jschoiRR** [comment]
@ycyun 에게 이슈 담당자 할당해주세요

**Comment by jschoiRR** [comment]
![image](https://user-images.githubusercontent.com/77760789/111280686-76617880-867f-11eb-8267-8cfea2d60c1c.png)

**Comment by ycyun** [comment]
- [ ] 클라우드센터 가상머신 동작상태
- [ ] 클라우드센터 가상머신 시작, 정지 관리
- [ ] 클라우드센터 가상머신 삭제
   [천강타책임](@kt-cheon)의 pcs 관리 명령어를 사용하여 위 기능들 UI에 연결
- [ ] 클라우드센터 가상머신 CPU, Memony등의 표시
   pcs를 사용해 어떤 호스트에 VM이 올라가있는지 확인후 해당 VM의 자원 할당량 표시

**Comment by ycyun** [comment]
현재 진행중인 화면입니다.
![image](https://user-images.githubusercontent.com/13939146/111722767-d76a9580-88a5-11eb-9e5d-a90da545a54e.png)
소켓, gw, nic type등을 가져오는 방법을 찾고있습니다.

**Comment by ycyun** [comment]
merge 되었으니 close 하겠습니다
