### ISSUE TITLE
SSH KEY 키 관리

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#36]
## 개발 개요
SSH KEY 키 관리 기능
## 개발 기능
ABLESTACK에서 사용할 SSH KEY를 관리하는 기능
신규 KEY 생성
Host KEY 다운로드
기존 KEY 업로드

**Comment by stardom3645** [comment]
제가 하겠습니다(류홍욱 주임)

**Comment by stardom3645** [comment]
- SSH-KEY 파일의 생성 및 기존 키 업로드 기능 개발 중
1. 기존 키 업로드 시, 개인키, 공동키 모두 필요하여 2개의 input 테그로 업로드 기능을 수행합니다.
2. cockpit API 사용 시 상대경로를 인식하지 못해 python파일을 사용하거나 경로를 절대경로로 하였습니다.
    파일 이름 : (ablecloud, ablecloud.pub)
    키 속성 : 패스워드(없음), 알고리즘(RSA2048), 덮어쓰기(TRUE), 키 형식(PEM)
    경로 : (/root/.ssh/)
3. 작동 프로세스 :  키 파일 생성 시에는 "다음" 버튼을 클릭 시 생성하고 기존 파일 업로드 시에는 파일을 선택하면 생성하게 됩니다.
