### ISSUE TITLE
/etc/hosts 관리

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#37]
## 개발 개요
/etc/hosts 에 IP 정보를 등록하고
편집을 위해 해당 파일을 사용자 PC로 다운로드 혹은 업로드를 하기 위한 기능개발
## 개발 기능
클러스터 구성 호스트의 수를 입력받음.(/etc/hosts 파일 다운로드, 업로드) 
호스트 : Mngt, HPN의 IP, 호스트명 
스토리지 센터 VM : Mngt, PN, CN의 IP 정보, 호스트명 
클라우드센터 VM : Mngt, Service 의 IP 정보, 호스트명 
## 기타
호스트명의 경우 하나만 입력받고, 나머지 이름은 prefix를 자동으로 붙여서 생성
ex)
input: 
host1, 192.168.0.11, 100.100.0.11, ablecloud1
host2, 192.168.0.12, 100.100.0.12, ablecloud2
cloud, 192.168.0.10, 172.16.0.1, ablecloud

/etc/hosts:
100.100.0.11 ablecloud1
100.100.0.12 ablecloud2
192.168.0.11 mablecloud1
192.168.0.12 mablecloud2
172.16.0.1 ablecloud
192.168.0.10 mablecloud

**Comment by stardom3645** [comment]
제가 하겠습니다(류홍욱 주임)
