### ISSUE TITLE
공통보안 처리

### ISSUE THREAD

**Issue by gigs4014** [ablecloud-team/ablestack-cockpit-plugin#382]
각 Core 서비스별 공통 보안처리

해당 보안처리는 국정원의 보안 기준으로 처리를 해야 하며, 보안기준 문서는 확보 후 공유예정

- [ ] #383
- [x] #384
- [ ] [Mold 보안처리](https://github.com/ablecloud-team/ablestack-cloud/issues/277)
- [ ] Works 보안처리
- [ ] Wall 보안처리

**Comment by Dajeong-Park** [comment]
* 국가정보원 보안요구사항 관련 문서 링크

https://www.nis.go.kr/AF/1_7_2_4/list.do?selectBox=0&fromDate=&toDate=2023-04-10&searchKeyword=&currentPage=1

* 국가정보원 공통보안요구사항 PDF

[(1,+2편)+해설+및+공통보안요구사항.pdf](https://github.com/ablecloud-team/ablestack-cockpit-plugin/files/11186752/1.%2B2.%2B.%2B.%2B.pdf)
