### ISSUE TITLE
시간서버 등록

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#39]
## 개발 개요
스토리지 클러스터의 정합성을 유지하기 위한 시간동기화를 할 수 있도록
시간동기화 서버를 설정하는 기능
## 개발 기능
NTP(timesyncd, chronyd등의 유사서비스 포함)의 주소 등록
Sample 설정파일 작성
## 기타
외부 시간서버 있을 경우와 없을 경우(자체 시간서버 구성)로 구분하여 기능제공 
외부 서버가 있는 경우 주소 등록 
외부 서버가 없는 경우, 자체 서버 정보를 입력 받고, 시간서버 확인하여 정상적일 때에 다음으로 넘어감(엔지니어가 자체 서버 구성, chrony.conf 파일을 샘플로 제공)

**Comment by stardom3645** [comment]
제가 하겠습니다(류홍욱 주임)

**Comment by kt-cheon** [comment]
외부 시간 서버가 없는 경우

호스트 IP를 (172.16.0.11, 172.16.0.12, 172.16.0.13) 이라고 가정하고,
/etc/chrony.conf 파일을 다음과 같이 수정해야 합니다.

1번 호스트 :
server 172.16.0.11 iburst minpoll 0 maxpoll 0
2번 호스트 :
server 172.16.0.11 prefer iburst minpoll 0 maxpoll 0
server 172.16.0.12 minpoll 0 maxpoll 0
3번 호스트 :
server 172.16.0.12 prefer iburst minpoll 0 maxpoll 0
server 172.16.0.11 minpoll 0 maxpoll 0

공통 부분 :
allow 172.16.0.0/24
local stratum 10

minpoll (default : 6, -6부터  24까지 설정 가능) , 예를 들어 -6으로 설정한 경우에는 1/64 초로 설정됨
maxpoll (default : 10, -6부터 24까지 설정가능)
