### ISSUE TITLE
클러스터 구성 준비 UI

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#40]
## 개발 개요
클러스터 구성 준비 UI
## 개발 기능
클러스터 구성 준비 UI

**Comment by stardom3645** [comment]
해당 이슈 할당 부탁드립니다.

**Comment by stardom3645** [comment]
- 클러스터 마법사 UI 확인 

- [vaildation 체크]  
- [ 파일 업로드 시 확장자 제한] 
- [키 업로드 구분 ]
