### ISSUE TITLE
클라우드센터 가상머신 XML 생성

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-cockpit-plugin#52]
## 개발 개요
클라우드센터 가상머신 XML 생성 기능
## 개발 기능
클라우드센터 가상머신 배포 마법사로 설정한 값으로 가상머신 환경설정 XML 파일 생성

**Comment by qoxown12** [comment]
제가 하겠습니다.

**Comment by kt-cheon** [comment]
ccvm.xml 구성은
  1. ceph auth key 등록
  2. virsh secret-key define
  3. rbd pool 목록 조회 기능
등이 포함 되어야 합니다.
