### ISSUE TITLE
스토리지 센터 가상머신 배포 전 초기화 기능

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-cockpit-plugin#66]
## 개발 개요
스토리지 센터 가상머신 배포 전 초기 세팅 구성 기능
스토리지 센터 가상머신을 배포하기 전에 배포에 사용할 scvm_template.xml과 scvm_template.qcow2 템플릿 파일을 scvm.xml과 scvm.qcow2로 복제하여 사용해야 원본 템플릿을 변경하지 않는다.

배포 실패 및 중단되거나 사용자가 스토리지 센터 가상머신을 삭제후 다시 생성하기 위해서는 이미 사용된 scvm.xml과 scvm.qcow2 파일을 삭제하고 다시 scvm_template.xml과 scvm_template.qcow2 복제하여 깨끗한 상태의 파일을 사용해야 한다.

또한 가상머신 배포후 cloudinit에 사용할 iso파일도 삭제하고 다시 반영 한다.
## 개발 기능
가상머신 scvm.xml 파일 삭제
가상머신 scvm.qcow2 파일 삭제
cloudinit iso 파일 삭제

가상머신 scvm_template.xml을 scvm.xml로 파일 복제 (깨끗한 상태로 xml 파싱 준비)
가상머신 scvm_template.qcow2을 scvm.qcow2로 파일 복제 (깨끗한 상태로 qcow2 사용 준비)

## 기타

**Comment by ycyun** [comment]
@qoxown12 #46 #54 작업시 초기 VM 생성시 디스크를 완전히 cp 로 복사하지 않고 
qemu-img create -F qcow2 -f qcow2 -b scvm_template.qcow2 scvm.qcow2
같은 방식으로 만들면 scvm_template을 parent로 하는 child 이미지가 만들어집니다.
그러면 원본 scvm_template.qcow2는 깨끗한 상태로 유지가 가능하고 전체를 복사하지 않으니 속도도 빠르니 참고하시면 좋을것 같습니다.

**Comment by qoxown12** [comment]
제가 하겠습니다.
