### ISSUE TITLE
스토리지센터 가상머신 상세조회

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#8]
## 개발 개요
스토리지센터 가상머신의 상세정보조회
## 개발 기능
스토리지센터 가상머신의 CPU, memory, 등의 설정 정보를 조회하는 기능

**Comment by jschoiRR** [comment]
제가하겠습니다.

**Comment by jschoiRR** [comment]
![Uploading image.png…]()
