### ISSUE TITLE
cloudinit 기능 개발

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit-plugin#86]
## 개발 개요
cloudinit iso 생성할것
#45 스토리지센터vm
#53 클라우드센터vm 필요 기능이 동일해 통합하면 좋을 것 같습니다.

## 개발 기능

- [x] iso생성
- [x] hosts 등록
- [x] sshkey등록
- [x] ip 입력
- [x] 본딩(optional)
- [x] 테스트

## 기타
cloudinit과 rpm은 미리 설치되어있는 qcow2파일 준비

**Comment by leca777** [comment]
#53 
#45 
두개의 이슈를 통합하여 본 이슈에서 진행합니다

**Comment by ycyun** [comment]
사용법은 다음과 같습니다.
ex) scvm
/usr/bin/python3 /root/cockpit-plugin-ablestack/tools/cloudinit/gencloudinit.py --hostname scvm1 \
    --pubkey /root/cockpit-plugin-ablestack/tools/cloudinit/id_rsa.pub \
    --privkey /root/cockpit-plugin-ablestack/tools/cloudinit/id_rsa \
    --hosts /root/cockpit-plugin-ablestack/tools/cloudinit/hosts \
    --mgmt-nic=ens12 --mgmt-ip 10.10.14.150 --mgmt-prefix 16 --mgmt-gw 10.10.0.1 --dns 8.8.8.8 \
    --pn-nic ens13 --pn-ip 10.10.14.151 \
    --cn-nic ens14 --cn-ip 10.10.14.152 --iso-path scvm.iso scvm

ex) ccvm
/usr/bin/python3 /root/cockpit-plugin-ablestack/tools/cloudinit/gencloudinit.py --hostname ccvm \
    --pubkey /root/cockpit-plugin-ablestack/tools/cloudinit/id_rsa.pub \
    --privkey /root/cockpit-plugin-ablestack/tools/cloudinit/id_rsa \
    --hosts /root/cockpit-plugin-ablestack/tools/cloudinit/hosts \
    --mgmt-nic=ens12 --mgmt-ip 10.10.14.150 --mgmt-prefix 16 --mgmt-gw 10.10.0.1 --dns 8.8.8.8 \
    --iso-path ccvm.iso ccvm
